{{ if and .Values.metrics.enabled .Values.metrics.server.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "icm-redis-cluster.fullname" . }}-metrics
  namespace: {{ with .Values.metrics.server.serviceMonitor.namespace }}{{ . }}{{ else }}{{ $.Release.Namespace }}{{ end }}
  labels: {{ include "icm-redis-cluster-metrics.labels" . | nindent 4 }}
    {{- with .Values.metrics.server.serviceMonitor.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  jobLabel: {{ include "icm-redis-cluster.fullname" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "icm-redis-cluster.name" . }}-metrics
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: metrics
  namespaceSelector:
    matchNames: [{{ .Release.Namespace }}]
  endpoints:
    - port: {{ .Values.metrics.server.port.name }}
      path: /metrics
      interval: {{ .Values.metrics.server.serviceMonitor.interval }}
{{ end }}
