{{- if include "icm-redis-cluster.hasextraconfig" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "icm-redis-cluster.fullname" . }}
  labels: {{- include "icm-redis-cluster.labels" . | nindent 4 }}
data:
  redis.conf: |-
{{- if .Values.redis.configuration.value }}
  {{- .Values.redis.configuration.value | nindent 4}}
{{- else -}}
  {{- (.Files.Get .Values.redis.configuration.file) | nindent 4 }}
{{- end }}
{{- end }}